name: Bonjour
on:
  - push
jobs:

  dire_bonjour:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      option: --user=root
    steps:
      - uses: actions/checkout@v5 #Récupère l'intégralité des fichiers du dépôts
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay 