name: vehicle-integration
on:
  - push
  - pull_request
jobs:

  installation_node:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5 #Récupère l'intégralité des fichiers du dépôts
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - run: npm ci
      - run: npm run build
      - run: ls dist/

