name: Vehicle Server CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Node
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Check Node Version
        run: node --version
      - name: Build application
        run: npm run build
      - name: Run Lint
        run: npm run lint
      - name: List dist output
        run: ls dist/