name: Bonjour
on:
  - push
jobs:

  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5 #Récupère l'intégralité des fichiers du dépôts
      - uses: juliangruber/read-file-action@v1
        id: cowsayid
        with:
          path: ./package.json

      - uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: "${{steps.cowsayid.outputs.content}}"